Fixed README.md, CRIU.new is undefined method.
```
% bundle exec ruby -e '
require "criu"
CRIU.new(
  images_dir: "/tmp/process_dump"
)'
Traceback (most recent call last):
-e:3:in `<main>': undefined method `new' for CRIU:Module (NoMethodError)
```