Fixed README.md, CRIU.target_pid is undefined method
```
% bundle exec ruby -ve '
require "criu"
CRIU._init_options
CRIU.images_dir = "/tmp/process_dump"
CRIU.target_pid = 123
'
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
Traceback (most recent call last):
-e:5:in `<main>': undefined method `target_pid=' for CRIU:Module (NoMethodError)
```